// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mcf.team.security.principal;

import com.mcf.team.security.principal.RolePrincipalAssignment;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect RolePrincipalAssignment_Roo_Configurable {
    
    declare @type: RolePrincipalAssignment: @Configurable;
    
}
