// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mcf.team;

import com.mcf.team.BidProject;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect BidProject_Roo_Configurable {
    
    declare @type: BidProject: @Configurable;
    
}
