// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mcf.team;

import com.mcf.team.Manager;
import com.mcf.team.Profile;

privileged aspect Manager_Roo_JavaBean {
    
    public Profile Manager.getProfile() {
        return this.profile;
    }
    
    public void Manager.setProfile(Profile profile) {
        this.profile = profile;
    }
    
}
